# Add this layer's configuration and classes to BBPATH.
BBPATH .= ":${LAYERDIR}"

# Discover recipes and recipe append files in this layer.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fzhub"
BBFILE_PATTERN_fzhub = "^${LAYERDIR}/"
BBFILE_PRIORITY_fzhub = "6"

LAYERDEPENDS_fzhub = "core rockchip"
LAYERSERIES_COMPAT_fzhub = "wrynose"
